server:
  port: 8088

---
spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8088/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: bookinfo
          uri: http://localhost:8081
          predicates:
            - Path=/bookinfoes/**
        - id: rentalManagement
          uri: http://localhost:8082
          predicates:
            - Path=/rentalManagements/**
        - id: delivery
          uri: http://localhost:8083
          predicates:
            - Path=/DeliveryManagements/**
        - id: lookup
          uri: http://localhost:8084
          predicates:
            - Path=/rentalStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: bookinfo
          uri: http://bookinfo:8080
          predicates:
            - Path=/bookinfoes/**
        - id: rentalManagement
          uri: http://rentalManagements:8080
          predicates:
            - Path=/rentalManagements/**
        - id: lookup
          uri: http://lookup:8080
          predicates:
            - Path=/rentalStatuses/**
        - id: delivery
          uri: http://DeliveryManagement:8080
          predicates:
            - Path=/DeliveryManagements/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080